import json
from typing import List, Dict

def get_extract_rules_prompt(raw_text: str) -> tuple[str, str]:
    system_instruction = (
        "You are an expert Enterprise Business Analyst.\n"
        "Your task is to analyze the natural language specification of a web application and extract formal Business Rules, Constraints, and detect Ambiguities.\n"
        "Return pure JSON with no markdown wrapping.\n\n"
        "{\n"
        "  \"rules\": [\n"
        "    {\n"
        "      \"rule_id\": \"R_EMAIL_REQUIRED\",\n"
        "      \"field\": \"<field_name>\",\n"
        "      \"rule_category\": \"validation\",\n"
        "      \"rule_operator\": \"<required|length_min|length_max|value_min|value_max|format|allowed_values|unique|dependency>\",\n"
        "      \"rule_value\": \"<threshold_or_regex_or_null>\",\n"
        "      \"source_text\": \"<exact original text mapped to this rule>\",\n"
        "      \"priority\": \"<high|medium|low>\",\n"
        "      \"confidence\": <float 0.0-1.0>,\n"
        "      \"description\": \"<clear Vietnamese description>\"\n"
        "    }\n"
        "  ],\n"
        "  \"constraints\": [\n"
        "    {\n"
        "      \"constraint_id\": \"C_AGE_VERIFICATION\",\n"
        "      \"when\": {\n"
        "        \"field\": \"<source_field>\",\n"
        "        \"operator\": \"<equal|not_equal|greater_than|less_than|in>\",\n"
        "        \"value\": \"<condition_value>\"\n"
        "      },\n"
        "      \"then\": {\n"
        "        \"field\": \"<target_field>\",\n"
        "        \"operator\": \"<required|equal|greater_than|less_than>\",\n"
        "        \"value\": \"<target_value>\"\n"
        "      },\n"
        "      \"source_text\": \"<exact original text>\",\n"
        "      \"confidence\": <float 0.0-1.0>,\n"
        "      \"description\": \"<clear Vietnamese description>\"\n"
        "    }\n"
        "  ],\n"
        "  \"ambiguities\": [\n"
        "    {\n"
        "      \"text\": \"<ambiguous phrase>\",\n"
        "      \"reason\": \"<why it is ambiguous>\",\n"
        "      \"candidate_values\": [\"<possible_value_1>\", \"<possible_value_2>\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
    )
    user_prompt = f"Extract enterprise business rules from this specification:\n{raw_text}"
    return system_instruction, user_prompt

def get_parse_spec_combined_prompt(raw_text: str) -> tuple[str, str]:
    """
    Combined prompt: extract Rules + Schema in ONE LLM call.
    Role: Senior QA Engineer + Business Analyst focused on test data generation.
    """
    system_instruction = (
        "You are a Senior QA Test Engineer and Enterprise Business Analyst.\n"
        "Your PRIMARY GOAL is to extract ALL validation rules from a software specification\n"
        "so that an automated test data generation system can produce high-quality test cases using:\n"
        "  - BVA (Boundary Value Analysis): test at min-1, min, min+1, max-1, max, max+1\n"
        "  - EP (Equivalence Partitioning): valid class, invalid-too-short, invalid-too-long, invalid-format\n"
        "  - Decision Table: combinations of valid/invalid fields\n"
        "  - Security: SQL injection, XSS script attempts\n\n"
        "EXTRACTION RULES:\n"
        "1. Every constraint mentioned in the spec must become a separate rule entry.\n"
        "2. For each numeric/string boundary, create BOTH a min rule AND a max rule.\n"
        "3. For 'allowed values', list ALL valid enum options in rule_value as JSON array string.\n"
        "4. For security constraints (no SQL, no script), use rule_operator='no_injection'.\n"
        "5. For regex constraints (only uppercase+digits), provide the actual regex pattern.\n"
        "6. 'required' fields must have a rule with rule_operator='required'.\n"
        "7. Optional fields must have a rule with rule_operator='optional'.\n\n"
        "Return ONLY pure JSON, no markdown, no explanation:\n\n"
        "{\n"
        "  \"rules\": [\n"
        "    {\n"
        "      \"rule_id\": \"R_PRODUCT_NAME_REQUIRED\",\n"
        "      \"field\": \"product_name\",\n"
        "      \"rule_category\": \"presence\",\n"
        "      \"rule_operator\": \"required\",\n"
        "      \"rule_value\": null,\n"
        "      \"bva_boundary\": null,\n"
        "      \"source_text\": \"productName: Bắt buộc\",\n"
        "      \"priority\": \"high\",\n"
        "      \"test_strategies\": [\"ep\", \"decision\"],\n"
        "      \"description\": \"Trường productName là bắt buộc\",\n"
        "      \"errorMessage\": \"Vui lòng nhập tên sản phẩm\"\n"
        "    },\n"
        "    {\n"
        "      \"rule_id\": \"R_PRODUCT_NAME_MIN_LENGTH\",\n"
        "      \"field\": \"product_name\",\n"
        "      \"rule_category\": \"length\",\n"
        "      \"rule_operator\": \"length_min\",\n"
        "      \"rule_value\": \"3\",\n"
        "      \"bva_boundary\": {\"min\": 3, \"bva_invalid_below\": 2, \"bva_valid_at\": 3, \"bva_valid_above\": 4},\n"
        "      \"source_text\": \"độ dài từ 3 đến 50 ký tự\",\n"
        "      \"priority\": \"high\",\n"
        "      \"test_strategies\": [\"bva\", \"ep\"],\n"
        "      \"description\": \"Độ dài tối thiểu 3 ký tự\",\n"
        "      \"errorMessage\": \"Tên sản phẩm phải từ 3 đến 50 ký tự\"\n"
        "    },\n"
        "    {\n"
        "      \"rule_id\": \"R_CATEGORY_ALLOWED_VALUES\",\n"
        "      \"field\": \"category\",\n"
        "      \"rule_category\": \"domain\",\n"
        "      \"rule_operator\": \"allowed_values\",\n"
        "      \"rule_value\": \"[\\\"Electronics\\\",\\\"Fashion\\\",\\\"Food\\\",\\\"Book\\\",\\\"Other\\\"]\",\n"
        "      \"bva_boundary\": null,\n"
        "      \"source_text\": \"phải thuộc một trong các nhóm\",\n"
        "      \"priority\": \"high\",\n"
        "      \"test_strategies\": [\"ep\", \"decision\"],\n"
        "      \"description\": \"Chỉ chấp nhận các giá trị trong danh sách\",\n"
        "      \"errorMessage\": \"Danh mục không hợp lệ\"\n"
        "    }\n"
        "  ],\n"
        "  \"constraints\": [\n"
        "    {\n"
        "      \"constraint_id\": \"C_ALL_REQUIRED_VALID\",\n"
        "      \"when\": {\"field\": \"_all_required_fields\", \"operator\": \"all_valid\", \"value\": \"true\"},\n"
        "      \"then\": {\"field\": \"_operation\", \"operator\": \"equal\", \"value\": \"SUCCESS\"},\n"
        "      \"source_text\": \"Chức năng thêm sản phẩm chỉ được thực hiện khi tất cả các trường bắt buộc hợp lệ\",\n"
        "      \"confidence\": 1.0,\n"
        "      \"description\": \"Hệ thống chỉ lưu khi toàn bộ dữ liệu hợp lệ\"\n"
        "    }\n"
        "  ],\n"
        "  \"ambiguities\": [\n"
        "    {\n"
        "      \"text\": \"<vague phrase>\",\n"
        "      \"reason\": \"<why it is unclear for test generation>\",\n"
        "      \"candidate_values\": [\"<option1>\", \"<option2>\"]\n"
        "    }\n"
        "  ],\n"
        "  \"fields\": [\n"
        "    {\n"
        "      \"name\": \"product_name\",\n"
        "      \"type\": \"string\",\n"
        "      \"data_type\": \"string\",\n"
        "      \"semantic_type\": \"text\",\n"
        "      \"required\": true,\n"
        "      \"minLength\": 3,\n"
        "      \"maxLength\": 50,\n"
        "      \"minValue\": null,\n"
        "      \"maxValue\": null,\n"
        "      \"regex\": \"^[a-zA-Z0-9\\\\s]+$\",\n"
        "      \"allowedValues\": null,\n"
        "      \"description\": \"Tên sản phẩm, chỉ chứa chữ cái, số và khoảng trắng\",\n"
        "      \"security_risk\": \"xss\",\n"
        "      \"inputType\": \"textbox\",\n"
        "      \"mapped_rules\": [\"R_PRODUCT_NAME_REQUIRED\", \"R_PRODUCT_NAME_MIN_LENGTH\"]\n"
        "    }\n"
        "  ]\n"
        "}\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "- Extract ONE rule per constraint (do not merge min and max into one rule).\n"
        "- For price/quantity with min/max: create separate R_xxx_MIN_VALUE and R_xxx_MAX_VALUE rules.\n"
        "- For string format rules: provide the actual regex in the 'fields' schema.\n"
        "- For security constraints (no SQL injection, no XSS): set rule_operator='no_injection' and set field's security_risk='sql_injection' or 'xss'.\n"
        "- Do NOT leave bva_boundary null for length or value rules - always fill in the boundary numbers.\n"
        "- The 'test_strategies' array tells the test generator which algorithms to use for this rule.\n"
        "- CRITICAL: MUST deduce a clear, user-facing 'errorMessage' in Vietnamese for EVERY rule (e.g., 'Email không hợp lệ').\n"
        "- CRITICAL: MUST deduce 'inputType' for fields (e.g., 'textbox', 'dropdown', 'datepicker', 'checkbox').\n"
        "- CRITICAL: Every field MUST have a 'type' from EXACTLY this list: [\"string\", \"number\", \"email\", \"card\", \"phone\", \"date\", \"boolean\"]. Do not use 'object' or 'array'. Flatten objects if necessary.\n"
    )
    user_prompt = (
        f"Analyze this software specification from a QA Test Engineering perspective.\n"
        f"Extract ALL rules needed to generate comprehensive test cases (BVA, EP, Decision Table, Security).\n"
        f"Do not miss any constraint, boundary value, format rule, or security requirement.\n\n"
        f"SPECIFICATION:\n{raw_text}"
    )
    return system_instruction, user_prompt



def get_generate_schema_prompt(rules: dict) -> tuple[str, str]:
    system_instruction = (
        "You are an expert System Architect.\n"
        "Based on the provided formal Business Rules, generate a JSON Schema for the data fields.\n"
        "Return pure JSON with no markdown wrapping.\n\n"
        "{\n"
        "  \"fields\": [\n"
        "    {\n"
        "      \"name\": \"<field_name in snake_case>\",\n"
        "      \"data_type\": \"<string|number|boolean>\",\n"
        "      \"semantic_type\": \"<email|card|phone|date|text|amount|percentage>\",\n"
        "      \"required\": <boolean>,\n"
        "      \"minLength\": <int|null>,\n"
        "      \"maxLength\": <int|null>,\n"
        "      \"minValue\": <float|null>,\n"
        "      \"maxValue\": <float|null>,\n"
        "      \"regex\": \"<regex string|null>\",\n"
        "      \"allowedValues\": [\"<val1>\"] | null,\n"
        "      \"description\": \"<Brief business meaning>\",\n"
        "      \"mapped_rules\": [\"R_EMAIL_REQUIRED\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
    )
    user_prompt = f"Generate schema based on these rules:\n{json.dumps(rules, ensure_ascii=False)}"
    return system_instruction, user_prompt

def get_generate_initial_population_prompt(schema: dict, rules: dict) -> tuple[str, str]:
    system_instruction = (
        "You are an expert QA Engineer.\n"
        "Generate a highly diverse Initial Population (F0 Dataset) of 5-8 test cases based on the schema and rules.\n"
        "Target: Valid cases, Boundary cases, and explicitly Invalid cases (violating EXACTLY one rule).\n"
        "Return pure JSON with no markdown wrapping.\n\n"
        "{\n"
        "  \"initialPopulation\": [\n"
        "    {\n"
        "      \"testcase_id\": \"TC-F0-001\",\n"
        "      \"data\": {\n"
        "        \"<field1>\": \"<val>\",\n"
        "        \"<field2>\": \"<val>\"\n"
        "      },\n"
        "      \"method\": \"<random|bva|ep|decision>\",\n"
        "      \"scenario\": \"<Vietnamese description>\",\n"
        "      \"expectedResult\": \"<VALID|INVALID>\",\n"
        "      \"violatedRule\": \"<rule_id or null>\",\n"
        "      \"coveredRules\": [\"<rule_id>\"]\n"
        "    }\n"
        "  ]\n"
        "}\n"
    )
    user_prompt = f"Schema:\n{json.dumps(schema, ensure_ascii=False)}\n\nRules:\n{json.dumps(rules, ensure_ascii=False)}\n\nGenerate F0 dataset."
    return system_instruction, user_prompt

def get_generate_seeds_prompt(fields: List[Dict], test_method: str, raw_text: str = "") -> tuple[str, str]:
    fields_str = json.dumps(fields, ensure_ascii=False)
    system_instruction = (
        "You are an expert QA Engineer and Data Generator.\n"
        f"Generate a JSON payload of 35-50 high-quality test cases based on the schema using the '{test_method}' method.\n"
        "IMPORTANT: Adhere strictly to the requested distribution of scenarios (e.g. 40% Valid, 30% Boundary, 20% Negative, 10% Pairwise) to maximize coverage.\n\n"
        "The returned JSON must EXACTLY follow this structure:\n"
        "{\n"
        "  \"initialPopulation\": [\n"
        "    {\n"
        "      \"data\": {\n"
        "        \"<field_name>\": \"<value>\"\n"
        "      },\n"
        "      \"method\": \"<test_method>\",\n"
        "      \"scenario\": \"<Vietnamese description of the scenario>\",\n"
        "      \"expectedResult\": \"<VALID|INVALID>\"\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "DO NOT include markdown, explanations, or code blocks. Output pure JSON."
    )
    user_prompt = f"Fields Schema: {fields_str}\nTesting Method: {test_method}\nOriginal Context (optional): {raw_text}\nGenerate test cases."
    return system_instruction, user_prompt

def get_evaluate_test_quality_prompt(fields: list, seeds: list, test_method: str, raw_text: str, deterministic_metrics: dict) -> tuple[str, str]:
    system_instruction = (
        "You are an expert QA Manager.\n"
        "Your role is to ANALYZE the deterministically calculated metrics of a dataset.\n"
        "Your response MUST be pure JSON matching this exact structure:\n"
        "{\n"
        "  \"score\": 85,\n"
        "  \"strengths\": [\"<strength 1 in Vietnamese>\"],\n"
        "  \"weaknesses\": [\"<weakness 1 in Vietnamese>\"],\n"
        "  \"missing_cases\": [\"<missing case>\"],\n"
        "  \"security_risks\": []\n"
        "}\n"
    )
    user_prompt = (
        f"Metrics from Engine: {json.dumps(deterministic_metrics)}\n\n"
        f"Fields Schema: {json.dumps(fields, ensure_ascii=False)}\n"
        f"Testing Method: {test_method}\n"
        f"Dataset: {json.dumps(seeds, ensure_ascii=False)}\n\n"
        "Explain the engine's evaluation in your JSON output."
    )
    return system_instruction, user_prompt

def get_evaluate_optimized_prompt(fields: list, dataset: list, algorithm: str, raw_text: str, deterministic_metrics: dict) -> tuple[str, str]:
    system_instruction = (
        "You are an elite QA Optimizer.\n"
        "Your role is to EXPLAIN the deterministic fitness and coverage scores produced by the Python backend engines.\n"
        "Your response MUST be pure JSON matching this exact structure:\n"
        "{\n"
        "  \"score\": 95,\n"
        "  \"boundary_edge_check\": {\n"
        "    \"status\": \"<STRONG/WEAK>\",\n"
        "    \"boundary_coverage\": \"<string representation of boundary_coverage_percent>\",\n"
        "    \"critical_hits\": 10,\n"
        "    \"description\": \"<Vietnamese explanation>\"\n"
        "  },\n"
        "  \"missing_cases\": [\"<missing case in Vietnamese>\"],\n"
        "  \"security_risks\": []\n"
        "}\n"
    )
    user_prompt = (
        f"Metrics from Engine: {json.dumps(deterministic_metrics)}\n\n"
        f"Algorithm Used: {algorithm}\n"
        f"Optimized Dataset (Top 30): {json.dumps(dataset[:30], ensure_ascii=False)}\n\n"
        "Explain the deterministic scores."
    )
    return system_instruction, user_prompt

def get_benchmark_analysis_prompt(benchmark_results: dict) -> tuple[str, str]:
    system_instruction = (
        "You are an expert QA Benchmarker and AI Test Platform Analyst.\n"
        "Review the quantitative results of the 6 test generation strategies (LLM, GA, HC, LLM_GA, LLM_HC, LLM_GA_HC).\n"
        "Provide a comprehensive Benchmark Scorecard in pure JSON.\n\n"
        "{\n"
        "  \"winner\": \"<Strategy Name>\",\n"
        "  \"ranking\": [\"<1st>\", \"<2nd>\", \"<3rd>\", \"<4th>\", \"<5th>\", \"<6th>\"],\n"
        "  \"strategy_scores\": {\n"
        "    \"LLM\": <0-100>,\n"
        "    \"LLM_GA_HC\": <0-100>\n"
        "  },\n"
        "  \"strengths\": [\"Điểm mạnh chung của các phương pháp hybrid\"],\n"
        "  \"weaknesses\": [\"Điểm yếu của phương pháp truyền thống\"],\n"
        "  \"recommendations\": [\"Khuyến nghị sử dụng trong dự án thực tế\"],\n"
        "  \"research_conclusion\": \"<Vietnamese deep conclusion>\"\n"
        "}\n"
    )
    user_prompt = f"Benchmark Results:\n{json.dumps(benchmark_results, ensure_ascii=False)}"
    return system_instruction, user_prompt
