import React, { useState } from 'react';
import type { Chromosome } from '../algorithms/genetic';
import { Download, FileSpreadsheet, FileJson, History, Database, AlertCircle, Trash2, Clock, ShieldAlert, Zap, Terminal, Code } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';

export const HistoryManager: React.FC = () => {
  const {
    optimizedDataset,
    historyRuns,
    handleLoadPastRun: onLoadPastRun,
    handleClearHistory: onClearHistory,
    schemaName,
    parsedSchema
  } = useAppStore();
  // Trạng thái (state) hiển thị thông báo đã sao chép chuỗi JSON vào bộ nhớ đệm
  const [copied, setCopied] = useState(false);
  // Trạng thái lọc loại ca kiểm thử trong bảng xem trước
  const [filterType, setFilterType] = useState<'all' | 'happy' | 'boundary' | 'security'>('all');
  // Số lượng bản ghi hiển thị trong bảng (có thể expand thêm)
  const [displayLimit, setDisplayLimit] = useState(30);

  // Trạng thái mô phỏng API Validation thời gian thực
  const [selectedRecord, setSelectedRecord] = useState<Chromosome | null>(null);
  const [selectedRecordIdx, setSelectedRecordIdx] = useState<number | null>(null);
  const [apiSimStatus, setApiSimStatus] = useState<'idle' | 'loading' | 'success' | 'validation_error' | 'waf_blocked'>('idle');
  const [apiSimDetails, setApiSimDetails] = useState<any>(null);
  
  // Trạng thái chạy hàng loạt (Batch Run All)
  const [batchRunning, setBatchRunning] = useState(false);
  const [batchProgress, setBatchProgress] = useState(0);
  const [batchSummary, setBatchSummary] = useState<{
    total: number;
    passed: number;
    validationErrors: number;
    wafBlocked: number;
  } | null>(null);

  // --- HÀM TRỢ GIÚP: TẠO TỆP TIN VÀ BẮT TRÌNH DUYỆT TẢI XUỐNG ---
  const downloadFile = (content: string, filename: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    
    URL.revokeObjectURL(url);
  };

  // --- HÀM XUẤT FILE CSV/EXCEL (ĐỊNH DẠNG BẢNG BIỂU) ---
  const handleExportCSV = () => {
    if (optimizedDataset.length === 0) return;
    
    const headers = Object.keys(optimizedDataset[0]);
    const csvRows = [headers.join(',')];

    optimizedDataset.forEach(row => {
      const values = headers.map(header => {
        const escaped = ('' + row[header]).replace(/"/g, '\\"');
        return `"${escaped}"`;
      });
      csvRows.push(values.join(','));
    });

    const csvContent = csvRows.join('\n');
    downloadFile(
      csvContent, 
      `${schemaName.toLowerCase().replace(/ /g, '_')}_dataset.csv`, 
      'text/csv;charset=utf-8;'
    );
  };

  // --- HÀM XUẤT FILE JSON ---
  const handleExportJSON = () => {
    if (optimizedDataset.length === 0) return;
    
    const jsonContent = JSON.stringify(optimizedDataset, null, 2);
    downloadFile(
      jsonContent, 
      `${schemaName.toLowerCase().replace(/ /g, '_')}_dataset.json`, 
      'application/json'
    );
  };

  // --- HÀM SAO CHÉP NHANH CHUỖI JSON ---
  const handleCopyClipboard = () => {
    if (optimizedDataset.length === 0) return;
    
    const jsonContent = JSON.stringify(optimizedDataset, null, 2);
    navigator.clipboard.writeText(jsonContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  // --- HÀM XUẤT SCRIPT PLAYWRIGHT (.spec.ts) ---
  const handleExportPlaywright = () => {
    if (optimizedDataset.length === 0) return;
    const safeSchemaName = schemaName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    const fields = Object.keys(optimizedDataset[0]);

    const scriptContent = `import { test, expect } from '@playwright/test';

/**
 * Playwright Automation Suite - Generated by Hyperion TestForge
 * Target Business Flow: ${schemaName}
 * Total Test Cases: ${optimizedDataset.length}
 */
test.describe('${schemaName} Automation Form Tests', () => {
  const testCases = ${JSON.stringify(optimizedDataset, null, 2)};

  testCases.forEach((data, index) => {
    test(\`Test Case #\${index + 1} - \${data.policyNumber || data.username || 'Record'} Verification\`, async ({ page }) => {
      // Step 1: Navigate to the target submission form
      await page.goto('https://your-app-domain.com/form-endpoint');
      
      // Step 2: Populate form fields with optimized data
      ${fields.map(field => `
      if (data.${field} !== undefined) {
        await page.fill('input[name="${field}"], #${field}', String(data.${field}));
      }`).join('\n')}

      // Step 3: Trigger the form submission
      await page.click('button[type="submit"], #submit-btn');

      // Step 4: Validate server-side response behavior
      const dataString = JSON.stringify(data);
      const isSecurityPayload = dataString.includes("'") || dataString.includes("<script") || dataString.includes("--");
      
      if (isSecurityPayload) {
        // Assert security protection blocks the submission (WAF blocked)
        const errorAlert = page.locator('.waf-alert, .forbidden, h1:has-text("403")');
        await expect(errorAlert).toBeVisible();
      } else {
        // Assert regular success toast or error validations
        // await expect(page.locator('.success-toast')).toBeVisible();
      }
    });
  });
});
`;
    downloadFile(scriptContent, `${safeSchemaName}_playwright.spec.ts`, 'application/typescript');
  };

  // --- HÀM XUẤT SCRIPT CYPRESS (.spec.js) ---
  const handleExportCypress = () => {
    if (optimizedDataset.length === 0) return;
    const safeSchemaName = schemaName.toLowerCase().replace(/[^a-z0-9]/g, '_');
    const fields = Object.keys(optimizedDataset[0]);

    const scriptContent = `/**
 * Cypress Automation Suite - Generated by Hyperion TestForge
 * Target Business Flow: ${schemaName}
 * Total Test Cases: ${optimizedDataset.length}
 */
describe('${schemaName} Automation Form Tests', () => {
  const testCases = ${JSON.stringify(optimizedDataset, null, 2)};

  testCases.forEach((data, index) => {
    it(\`Test Case #\${index + 1} - \${data.policyNumber || data.username || 'Record'} Verification\`, () => {
      // Step 1: Navigate to the target submission form
      cy.visit('/form-endpoint');
      
      // Step 2: Populate form fields with optimized data
      ${fields.map(field => `
      if (data.${field} !== undefined) {
        cy.get('input[name="${field}"], #${field}').clear().type(String(data.${field}));
      }`).join('\n')}

      // Step 3: Trigger form submission
      cy.get('button[type="submit"], #submit-btn').click();

      // Step 4: Validate server-side response behavior
      const dataString = JSON.stringify(data);
      const isSecurityPayload = dataString.includes("'") || dataString.includes("<script") || dataString.includes("--");

      if (isSecurityPayload) {
        cy.contains('403').should('be.visible');
      } else {
        // cy.get('.success-message').should('be.visible');
      }
    });
  });
});
`;
    downloadFile(scriptContent, `${safeSchemaName}_cypress.spec.js`, 'application/javascript');
  };

  // --- HÀM CHẠY HÀNG LOẠT (BATCH RUN ALL) ---
  const handleBatchRunAll = async () => {
    if (optimizedDataset.length === 0 || batchRunning) return;
    setBatchRunning(true);
    setBatchProgress(0);
    setBatchSummary(null);
    setApiSimStatus('idle');
    setSelectedRecord(null);

    let passed = 0;
    let validationErrors = 0;
    let wafBlocked = 0;
    const total = optimizedDataset.length;

    for (let i = 0; i < total; i++) {
      const record = optimizedDataset[i];
      setBatchProgress(Math.round(((i + 1) / total) * 100));

      // Kiểm tra WAF
      let isSecurity = false;
      let isValidationError = false;
      Object.keys(record).forEach(key => {
        const valStr = String(record[key]);
        if (valStr.includes("'") || valStr.includes('<script') || valStr.includes('--')) {
          isSecurity = true;
        }
      });
      if (isSecurity) { wafBlocked++; continue; }

      // Kiểm tra validation
      Object.keys(record).forEach(key => {
        const val = record[key];
        const valStr = String(val);
        if (key === 'email' || key === 'beneficiaryEmail') {
          if (!valStr.includes('@') || !valStr.includes('.')) isValidationError = true;
        }
        if (key === 'phone' && !/^(03|05|07|08|09)\d{8}$/.test(valStr)) isValidationError = true;
        if (key === 'cardNumber' && !/^\d{16}$/.test(valStr)) isValidationError = true;
        if (key === 'cvv' && !/^\d{3}$/.test(valStr)) isValidationError = true;
        if (key === 'age') { const n = Number(val); if (isNaN(n) || n < 18 || n > 100) isValidationError = true; }
        if (key === 'amount') { const n = Number(val); if (isNaN(n) || n < 1 || n > 50000) isValidationError = true; }
        if (key === 'username' && (valStr.length < 5 || valStr.length > 15 || !/^[a-zA-Z0-9]+$/.test(valStr))) isValidationError = true;
      });

      if (isValidationError) { validationErrors++; } else { passed++; }
      
      // Giả lập độ trễ 5ms giữa mỗi ca
      await new Promise(res => setTimeout(res, 5));
    }

    setBatchSummary({ total, passed, validationErrors, wafBlocked });
    setBatchRunning(false);
    setBatchProgress(100);
  };

  // --- HÀM MÔ PHỎNG PHẢN HỒI API (LIVE API RESPONSE SIMULATOR) ---
  const handleSimulateAPI = (record: Chromosome, index: number) => {
    setSelectedRecord(record);
    setSelectedRecordIdx(index);
    setApiSimStatus('loading');
    
    setTimeout(() => {
      let isSecurity = false;
      let isValidationError = false;
      const errors: Record<string, string> = {};

      // 1. Security Check (WAF blocks)
      Object.keys(record).forEach(key => {
        const valStr = String(record[key]);
        if (valStr.includes("'") || valStr.includes("<script") || valStr.includes("--")) {
          isSecurity = true;
        }
      });

      if (isSecurity) {
        setApiSimStatus('waf_blocked');
        setApiSimDetails({
          status: 403,
          statusText: 'Forbidden (Blocked by WAF)',
          message: 'BỊ CHẶN BỞI TƯỜNG LỬA (WAF BLOCK): Phát hiện mẫu ký tự bất thường hoặc payload tấn công độc hại!',
          wafRule: 'OWASP-CRS-V3.3-SQL-INJECTION-DETECTION',
          signature: 'SIGNATURE-BLOCK#XSS-SQLi-ALERT-2026',
          timestamp: new Date().toISOString(),
          ipAddress: '103.48.15.22',
          userAgent: 'Mozilla/5.0 (Playwright-Agent; Headless)'
        });
        return;
      }

      // 2. Validation Check
      Object.keys(record).forEach(key => {
        const val = record[key];
        const valStr = String(val);

        if (key === 'email' || key === 'beneficiaryEmail') {
          if (!valStr.includes('@') || !valStr.includes('.')) {
            isValidationError = true;
            errors[key] = 'Địa chỉ email không đúng định dạng RFC 5322 (Thiếu ký tự "@" hoặc phần mở rộng tên miền).';
          }
        }
        
        if (key === 'phone') {
          if (!/^(03|05|07|08|09)\d{8}$/.test(valStr)) {
            isValidationError = true;
            errors[key] = 'Số điện thoại không đúng định dạng mạng viễn thông Việt Nam (Cần bắt đầu bằng 03/05/07/08/09 và dài đúng 10 số).';
          }
        }

        if (key === 'cardNumber') {
          if (!/^\d{16}$/.test(valStr)) {
            isValidationError = true;
            errors[key] = 'Mã số thẻ thanh toán không hợp lệ (Phải là chuỗi gồm đúng 16 ký tự số nguyên dương).';
          }
        }

        if (key === 'cvv') {
          if (!/^\d{3}$/.test(valStr)) {
            isValidationError = true;
            errors[key] = 'Mã số CVV bảo mật không hợp lệ (Phải là chuỗi dài đúng 3 ký tự số).';
          }
        }

        if (key === 'policyNumber') {
          if (!/^[A-Z]{3}-\d{6}$/.test(valStr)) {
            isValidationError = true;
            errors[key] = 'Mã đơn bảo hiểm VIP không hợp lệ (Phải tuân thủ định dạng 3 chữ cái viết hoa đầu, theo sau bởi dấu gạch ngang và 6 chữ số, e.g., POL-123456).';
          }
        }

        if (key === 'age') {
          const num = Number(val);
          if (isNaN(num) || num < 18 || num > 100) {
            isValidationError = true;
            errors[key] = 'Độ tuổi tham gia không đáp ứng biên quy định (Phải từ 18 tuổi đến 100 tuổi).';
          }
        }

        if (key === 'amount') {
          const num = Number(val);
          if (isNaN(num) || num < 1 || num > 50000) {
            isValidationError = true;
            errors[key] = 'Số tiền giao dịch vượt ngoài biên cho phép (Yêu cầu lớn hơn 0 và tối đa 50,000 USD).';
          }
        }

        if (key === 'monthlyIncome') {
          const num = Number(val);
          if (isNaN(num) || num < 10000 || num > 1000000) {
            isValidationError = true;
            errors[key] = 'Thu nhập hàng tháng của VIP nằm ngoài biên phê duyệt bảo hiểm (Yêu cầu tối thiểu từ 10,000 USD đến 1,000,000 USD).';
          }
        }

        if (key === 'preExistingConditions') {
          const allowed = ['None', 'HeartDisease', 'Diabetes', 'Hypertension'];
          if (!allowed.includes(valStr)) {
            isValidationError = true;
            errors[key] = `Tình trạng bệnh lý nền không nằm trong danh mục kê khai cho phép: ${allowed.join(', ')}.`;
          }
        }

        if (key === 'username') {
          if (valStr.length < 5 || valStr.length > 15 || !/^[a-zA-Z0-9]+$/.test(valStr)) {
            isValidationError = true;
            errors[key] = 'Tên đăng nhập không đúng đặc tả (Yêu cầu độ dài 5-15 ký tự và chỉ chứa chữ cái hoặc số).';
          }
        }

        if (key === 'fullName') {
          if (valStr.length < 2 || valStr.length > 50) {
            isValidationError = true;
            errors[key] = 'Họ và tên không hợp lệ (Độ dài yêu cầu từ 2 đến 50 ký tự học thuật chuẩn).';
          }
        }
      });

      if (isValidationError) {
        setApiSimStatus('validation_error');
        setApiSimDetails({
          status: 400,
          statusText: 'Bad Request',
          message: 'LỖI KIỂM DUYỆT (VALIDATION ERROR): Một hoặc nhiều trường dữ liệu không đáp ứng ràng buộc nghiệp vụ.',
          errors,
          timestamp: new Date().toISOString()
        });
      } else {
        setApiSimStatus('success');
        setApiSimDetails({
          status: 200,
          statusText: 'OK',
          message: 'GỬI YÊU CẦU THÀNH CÔNG (SUCCESS): Bản ghi dữ liệu hoàn toàn hợp lệ, form đã được phê duyệt.',
          transactionId: `TXN-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
          timestamp: new Date().toISOString()
        });
      }
    }, 800);
  };

  // --- PHÂN LOẠI CA KIỂM THỬ ĐỂ HỖ TRỢ BỘ LỌC CHÍNH XÁC ---
  const getRowCategory = (row: Chromosome): 'happy' | 'boundary' | 'security' => {
    let isSecurity = false;
    const securityKeywords = ["' or", '" or', "'or", '"or', '--', 'union', 'select', 'drop table', '<script', 'onload=', 'onerror=', 'javascript:'];
    
    // 1. Kiểm tra an ninh (Security)
    Object.values(row).forEach(val => {
      const str = String(val).toLowerCase();
      if (securityKeywords.some(kw => str.includes(kw))) {
        isSecurity = true;
      }
    });
    if (isSecurity) return 'security';

    // 2. Kiểm tra biên (Boundary) dựa trên parsedSchema
    let isBoundary = false;
    parsedSchema.forEach(field => {
      const val = row[field.name];
      if (val !== undefined && val !== null) {
        const strVal = String(val);
        if (field.type === 'number') {
          const num = Number(val);
          if (!isNaN(num)) {
            if (field.minValue !== undefined && num === field.minValue) isBoundary = true;
            if (field.maxValue !== undefined && num === field.maxValue) isBoundary = true;
          }
        } else {
          if (field.minLength !== undefined && strVal.length === field.minLength) isBoundary = true;
          if (field.maxLength !== undefined && strVal.length === field.maxLength) isBoundary = true;
        }
      }
    });

    if (isBoundary) return 'boundary';
    return 'happy';
  };

  // Áp dụng phân loại và lọc
  const categorizedDataset = optimizedDataset.map((row, idx) => ({
    row,
    idx,
    category: getRowCategory(row)
  }));

  const filteredDataset = categorizedDataset.filter(item => {
    if (filterType === 'all') return true;
    return item.category === filterType;
  });

  // Đếm số lượng ca test cho từng tab bộ lọc
  const totalCount = optimizedDataset.length;
  const happyCount = categorizedDataset.filter(i => i.category === 'happy').length;
  const boundaryCount = categorizedDataset.filter(i => i.category === 'boundary').length;
  const securityCount = categorizedDataset.filter(i => i.category === 'security').length;

  return (
    <div className="flex flex-col gap-lg" style={{ marginTop: '16px', width: '100%' }}>
      <div className="grid-2" style={{ gap: '20px' }}>
      
      {/* CỘT BÊN TRÁI: KHÔNG GIAN ĐIỀU KHIỂN XUẤT DỮ LIỆU & LỊCH SỬ PHIÊN CHẠY */}
      <div className="glass-card flex flex-col gap-md teal-border" style={{ background: 'rgba(15, 23, 42, 0.4)' }}>
        <div className="flex align-center gap-sm" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '10px' }}>
          <History className="text-teal" size={22} style={{ color: 'var(--color-teal)' }} />
          <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#fff', letterSpacing: '0.03em' }}>TRUNG TÂM XUẤT DỮ LIỆU &amp; LỊCH SỬ</h2>
        </div>

        <p style={{ color: 'var(--text-secondary)', fontSize: '13px', lineHeight: '1.5' }}>
          Tải xuống trực tiếp tập ca kiểm thử tối ưu hóa đã sinh dưới định dạng CSV/Excel hoặc JSON để đưa trực tiếp vào các công cụ tự động hóa như Selenium, Playwright, Postman.
        </p>

        {/* NÚT XUẤT FILE CHỈ HIỂN THỊ KHI ĐÃ CÓ DỮ LIỆU TỐI ƯU HÓA */}
        {optimizedDataset.length > 0 ? (
          <div className="flex flex-col gap-sm" style={{ margin: '6px 0' }}>
            <div className="flex gap-sm">
              <button 
                onClick={handleExportCSV} 
                className="btn btn-primary" 
                style={{ 
                  flex: 1, 
                  fontSize: '13px', 
                  padding: '10px 14px',
                  background: 'linear-gradient(135deg, var(--color-teal) 0%, #0d9488 100%)', 
                  border: 'none',
                  color: '#fff',
                  fontWeight: '600'
                }}
              >
                <FileSpreadsheet size={16} /> Xuất CSV / Excel
              </button>
              
              <button 
                onClick={handleExportJSON} 
                className="btn btn-secondary" 
                style={{ 
                  flex: 1, 
                  fontSize: '13px', 
                  padding: '10px 14px',
                  borderColor: 'rgba(255,255,255,0.1)',
                  fontWeight: '600'
                }}
              >
                <FileJson size={16} /> Xuất File JSON
              </button>
            </div>
            
            <button 
              onClick={handleCopyClipboard} 
              className="btn btn-secondary" 
              style={{ 
                fontSize: '13px', 
                padding: '10px 14px', 
                background: copied ? 'rgba(45,212,191,0.06)' : 'rgba(255,255,255,0.01)',
                borderColor: copied ? 'var(--color-teal)' : 'rgba(255,255,255,0.08)',
                color: copied ? 'var(--color-teal)' : '#94a3b8',
                fontWeight: '600',
                transition: 'all 0.3s'
              }}
            >
              <Download size={16} /> 
              {copied ? 'Đã sao chép chuỗi JSON!' : 'Sao chép chuỗi JSON nhanh'}
            </button>

            {/* Automation Exporters */}
            <div className="flex gap-sm" style={{ marginTop: '4px' }}>
              <button 
                onClick={handleExportPlaywright} 
                className="btn btn-secondary" 
                style={{ 
                  flex: 1, 
                  fontSize: '11px', 
                  padding: '10px 12px',
                  borderColor: 'rgba(45, 212, 191, 0.2)',
                  color: 'var(--color-teal)',
                  background: 'rgba(45, 212, 191, 0.02)',
                  fontWeight: '600',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '6px'
                }}
              >
                <Terminal size={13} /> Playwright Spec
              </button>
              
              <button 
                onClick={handleExportCypress} 
                className="btn btn-secondary" 
                style={{ 
                  flex: 1, 
                  fontSize: '11px', 
                  padding: '10px 12px',
                  borderColor: 'rgba(167, 139, 250, 0.2)',
                  color: 'var(--color-violet)',
                  background: 'rgba(167, 139, 250, 0.02)',
                  fontWeight: '600',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '6px'
                }}
              >
                <Code size={13} /> Cypress Spec
              </button>
            </div>
          </div>

        ) : (
          <div className="flex align-center gap-sm" style={{ padding: '16px', background: 'rgba(255,255,255,0.01)', border: '1px dashed rgba(255,255,255,0.06)', borderRadius: 'var(--radius-sm)', color: 'var(--text-muted)', fontSize: '13px', justifyContent: 'center' }}>
            <AlertCircle size={16} /> Hãy chạy tối ưu hóa ở Tab "Tối Ưu Hóa Bộ Test" để xuất dữ liệu.
          </div>
        )}

        {/* DANH SÁCH LỊCH SỬ CÁC LƯỢT CHẠY TRONG PHIÊN */}
        <div className="flex flex-col gap-sm" style={{ marginTop: '10px' }}>
          <div className="flex justify-between align-center" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '6px' }}>
            <h4 style={{ fontSize: '13px', fontWeight: 'bold', color: 'var(--text-secondary)' }}>
              Lịch sử các phiên chạy đã lưu
            </h4>
            {historyRuns.length > 0 && onClearHistory && (
              <button 
                onClick={onClearHistory}
                className="btn btn-secondary flex align-center gap-xs" 
                style={{ padding: '2px 8px', fontSize: '11px', color: 'var(--color-rose)', borderColor: 'rgba(244,63,94,0.1)' }}
              >
                <Trash2 size={12} /> Xóa sạch
              </button>
            )}
          </div>
          
          <div className="flex flex-col gap-sm" style={{ maxHeight: '200px', overflowY: 'auto', paddingRight: '4px' }}>
            {historyRuns.length === 0 ? (
              <span style={{ fontSize: '12px', color: 'var(--text-muted)', textAlign: 'center', padding: '24px 0', border: '1px dashed rgba(255,255,255,0.03)', borderRadius: 'var(--radius-sm)' }}>
                Chưa có lượt chạy thành công nào được lưu trữ.
              </span>
            ) : (
              historyRuns.map((run, idx) => (
                <div 
                  key={idx} 
                  className="flex justify-between align-center card-hover-animation"
                  style={{ 
                    background: 'rgba(255,255,255,0.02)', 
                    border: '1px solid rgba(255,255,255,0.05)', 
                    padding: '10px 14px', 
                    borderRadius: '8px',
                    fontSize: '12px',
                    transition: 'all 0.3s'
                  }}
                >
                  <div className="flex flex-col gap-xs">
                    <span style={{ fontWeight: 'bold', color: 'var(--color-teal)', fontSize: '12.5px' }}>{run.schemaName}</span>
                    <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      <Clock size={10} /> {run.timestamp}
                    </span>
                  </div>
                  <div className="flex align-center gap-md">
                    <div style={{ textAlign: 'right' }}>
                      <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 'bold', color: '#fff' }}>{(run.coverage * 100).toFixed(0)}%</span>
                      <div style={{ fontSize: '9px', color: 'var(--text-muted)' }}>Độ phủ</div>
                    </div>
                    <button 
                      onClick={() => onLoadPastRun(run.data)}
                      className="btn btn-secondary" 
                      style={{ padding: '6px 12px', fontSize: '11px', fontWeight: 'bold', borderColor: 'rgba(45,212,191,0.2)', color: 'var(--color-teal)' }}
                    >
                      Nạp lại
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
 
      {/* CỘT BÊN PHẢI: BẢNG XEM TRƯỚC BẢN GHI DỮ LIỆU CHI TIẾT */}
      <div className="glass-card flex flex-col gap-md violet-border" style={{ background: 'rgba(15, 23, 42, 0.4)' }}>
        <div className="flex justify-between align-center" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '10px' }}>
          <div className="flex align-center gap-sm">
            <Database className="text-violet" size={22} style={{ color: 'var(--color-violet)' }} />
            <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#fff', letterSpacing: '0.03em' }}>XEM TRƯỚC BỘ CA KIỂM THỬ</h2>
          </div>
          {optimizedDataset.length > 0 && (
            <span style={{ fontSize: '11px', background: 'rgba(167,139,250,0.1)', color: 'var(--color-violet)', padding: '2px 8px', borderRadius: '12px', fontWeight: 'bold' }}>
              Tổng cộng: {optimizedDataset.length} ca test
            </span>
          )}
        </div>

        {optimizedDataset.length > 0 ? (
          <div className="flex flex-col gap-md" style={{ flex: 1 }}>
            
            {/* THANH BỘ LỌC THÔNG MINH (QA CATEGORY FILTERS) */}
            <div className="flex gap-xs" style={{ flexWrap: 'wrap', background: 'rgba(15, 23, 42, 0.4)', padding: '4px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
              <button 
                onClick={() => setFilterType('all')}
                style={{ 
                  flex: 1, minWidth: '80px', padding: '6px 8px', border: 'none', borderRadius: '6px', fontSize: '11.5px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s',
                  background: filterType === 'all' ? 'rgba(255,255,255,0.08)' : 'transparent',
                  color: filterType === 'all' ? '#fff' : 'var(--text-muted)'
                }}
              >
                Tất cả ({totalCount})
              </button>
              <button 
                onClick={() => setFilterType('happy')}
                style={{ 
                  flex: 1, minWidth: '95px', padding: '6px 8px', border: 'none', borderRadius: '6px', fontSize: '11.5px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s',
                  background: filterType === 'happy' ? 'rgba(45,212,191,0.08)' : 'transparent',
                  color: filterType === 'happy' ? 'var(--color-teal)' : 'var(--text-muted)'
                }}
              >
                🟢 Positive ({happyCount})
              </button>
              <button 
                onClick={() => setFilterType('boundary')}
                style={{ 
                  flex: 1, minWidth: '95px', padding: '6px 8px', border: 'none', borderRadius: '6px', fontSize: '11.5px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s',
                  background: filterType === 'boundary' ? 'rgba(167,139,250,0.08)' : 'transparent',
                  color: filterType === 'boundary' ? 'var(--color-violet)' : 'var(--text-muted)'
                }}
              >
                🟡 Rìa Biên ({boundaryCount})
              </button>
              <button 
                onClick={() => setFilterType('security')}
                style={{ 
                  flex: 1, minWidth: '95px', padding: '6px 8px', border: 'none', borderRadius: '6px', fontSize: '11.5px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s',
                  background: filterType === 'security' ? 'rgba(244,63,94,0.08)' : 'transparent',
                  color: filterType === 'security' ? 'var(--color-rose)' : 'var(--text-muted)'
                }}
              >
                🔴 An Ninh ({securityCount})
              </button>
            </div>

            {/* BẢNG DỮ LIỆU HIỂN THỊ SAU KHI LỌC */}
            <div style={{ flex: 1, width: '100%', overflowX: 'auto', maxHeight: '310px', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '8px' }}>
              {filteredDataset.length === 0 ? (
                <div style={{ padding: '48px', color: 'var(--text-muted)', textAlign: 'center', fontSize: '13px' }}>
                  Không tìm thấy ca kiểm thử nào khớp với bộ lọc này.
                </div>
              ) : (
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px', textAlign: 'left' }}>
                  <thead>
                    <tr style={{ background: 'rgba(15,23,42,0.8)', borderBottom: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-muted)' }}>
                      <th style={{ padding: '10px 12px', width: '80px' }}>Phân Loại</th>
                      {Object.keys(optimizedDataset[0]).map(k => (
                        <th key={k} style={{ padding: '10px 12px' }}>{k}</th>
                      ))}
                      <th style={{ padding: '10px 12px', width: '90px', textAlign: 'center' }}>Hành Động</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredDataset.slice(0, displayLimit).map(({ row, idx, category }) => {
                      return (
                        <tr 
                          key={idx} 
                          style={{ 
                            borderBottom: '1px solid rgba(255,255,255,0.04)',
                            background: category === 'security' ? 'rgba(244,63,94,0.03)' : category === 'boundary' ? 'rgba(167,139,250,0.03)' : 'none'
                          }}
                        >
                          {/* Render badge phân loại */}
                          <td style={{ padding: '10px 12px' }}>
                            <span 
                              style={{ 
                                padding: '2px 6px', 
                                borderRadius: '4px', 
                                fontSize: '9.5px', 
                                fontWeight: 'bold',
                                background: category === 'security' ? 'rgba(244,63,94,0.15)' : category === 'boundary' ? 'rgba(167,139,250,0.15)' : 'rgba(45,212,191,0.15)',
                                color: category === 'security' ? 'var(--color-rose)' : category === 'boundary' ? 'var(--color-violet)' : 'var(--color-teal)'
                              }}
                            >
                              {category === 'security' ? 'AN NINH' : category === 'boundary' ? 'RÌA BIÊN' : 'POSITIVE'}
                            </span>
                          </td>
                          {Object.keys(row).map(k => {
                            const valStr = String(row[k]);
                            const isSpecial = valStr.includes("'") || valStr.includes("<script") || valStr === "" || valStr === "0";
                            return (
                              <td 
                                key={k} 
                                title={valStr} // Tooltip khi hover xem đầy đủ payload
                                style={{ 
                                  padding: '10px 12px', 
                                  fontFamily: 'var(--font-mono)',
                                  color: category === 'security' && (valStr.includes("'") || valStr.includes("<script") || valStr.includes("--")) ? 'var(--color-rose)' : 'inherit',
                                  fontWeight: isSpecial ? 'bold' : 'normal',
                                  // Giới hạn độ dài, tránh vỡ cột bảng
                                  maxWidth: '180px',
                                  overflow: 'hidden',
                                  textOverflow: 'ellipsis',
                                  whiteSpace: 'nowrap'
                                }}
                              >
                                {valStr === '' ? <i style={{ color: 'var(--text-muted)' }}>(Chuỗi rỗng / Empty)</i> : valStr}
                              </td>
                            );
                          })}
                          <td style={{ padding: '10px 12px', textAlign: 'center' }}>
                            <button 
                              onClick={() => handleSimulateAPI(row, idx)}
                              className="btn btn-secondary"
                              style={{ 
                                padding: '4px 8px', 
                                fontSize: '10.5px', 
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '4px',
                                border: '1px solid',
                                borderColor: selectedRecordIdx === idx ? 'var(--color-teal)' : 'rgba(255,255,255,0.08)',
                                color: selectedRecordIdx === idx ? 'var(--color-teal)' : 'var(--text-secondary)',
                                background: selectedRecordIdx === idx ? 'rgba(45,212,191,0.08)' : 'rgba(255,255,255,0.01)',
                                cursor: 'pointer',
                                borderRadius: '4px',
                                transition: 'all 0.2s',
                                fontWeight: '600'
                              }}
                            >
                              <Zap size={10} /> Test API
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              )}
              
              {/* NÚT XEM THÊM / THU GỌN */}
              {filteredDataset.length > displayLimit ? (
                <div style={{ textAlign: 'center', padding: '10px', background: 'rgba(15,23,42,0.4)', borderTop: '1px solid rgba(255,255,255,0.05)', display: 'flex', justifyContent: 'center', gap: '10px' }}>
                  <button
                    onClick={() => setDisplayLimit(prev => prev + 30)}
                    style={{ fontSize: '11.5px', padding: '6px 16px', background: 'rgba(45,212,191,0.06)', border: '1px solid rgba(45,212,191,0.2)', borderRadius: '6px', color: 'var(--color-teal)', cursor: 'pointer', fontWeight: 'bold' }}
                  >
                    ↓ Xem thêm {Math.min(30, filteredDataset.length - displayLimit)} ca ({filteredDataset.length - displayLimit} còn lại)
                  </button>
                </div>
              ) : filteredDataset.length > 30 ? (
                <div style={{ textAlign: 'center', padding: '10px', background: 'rgba(15,23,42,0.4)', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
                  <button
                    onClick={() => setDisplayLimit(30)}
                    style={{ fontSize: '11.5px', padding: '6px 16px', background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '6px', color: 'var(--text-muted)', cursor: 'pointer' }}
                  >
                    ↑ Thu gọn
                  </button>
                </div>
              ) : null}
            </div>
            
            {/* LƯU Ý BẢO MẬT DƯỚI ĐÁY */}
            <div className="flex align-center gap-sm" style={{ padding: '8px 12px', background: 'rgba(244,63,94,0.04)', border: '1px solid rgba(244,63,94,0.1)', borderRadius: '6px', fontSize: '11px', color: 'var(--color-rose)', marginTop: 'auto' }}>
              <ShieldAlert size={14} style={{ flexShrink: 0 }} />
              <span><b>Lưu ý an toàn:</b> Các chuỗi XSS/SQLi tấn công được sinh ra nhằm mục đích dò quét an ninh phần mềm. Đã mã hóa HTML khi render, tránh dán trực tiếp vào DB sản xuất của bạn.</span>
            </div>
          </div>
        ) : (
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px dashed rgba(255,255,255,0.05)', borderRadius: 'var(--radius-sm)', background: 'rgba(255,255,255,0.01)', padding: '80px 0', color: 'var(--text-muted)' }}>
            Chưa có tập dữ liệu tối ưu hóa nào được sinh ra.
          </div>
        )}
      </div>
      </div> {/* CLOSE grid-2 */}

      {/* PHÂN VÙNG MỚI: BỘ MÔ PHỎNG PHẢN HỒI API VALIDATION THỜI GIAN THỰC */}
      {optimizedDataset.length > 0 && (
        <div 
          className="glass-card flex flex-col gap-md"
          style={{ 
            background: 'rgba(15, 23, 42, 0.55)', 
            border: '1px solid',
            borderColor: 
              apiSimStatus === 'success' ? 'rgba(45, 212, 191, 0.4)' : 
              apiSimStatus === 'validation_error' ? 'rgba(167, 139, 250, 0.4)' : 
              apiSimStatus === 'waf_blocked' ? 'rgba(244, 63, 94, 0.5)' : 
              apiSimStatus === 'loading' ? 'rgba(59, 130, 246, 0.5)' : 'rgba(255,255,255,0.06)',
            boxShadow: 
              apiSimStatus === 'success' ? '0 0 15px rgba(45, 212, 191, 0.1)' : 
              apiSimStatus === 'validation_error' ? '0 0 15px rgba(167, 139, 250, 0.1)' : 
              apiSimStatus === 'waf_blocked' ? '0 0 20px rgba(244, 63, 94, 0.15)' : 
              apiSimStatus === 'loading' ? '0 0 15px rgba(59, 130, 246, 0.1)' : 'none',
            padding: '20px',
            borderRadius: '12px',
            transition: 'all 0.3s ease'
          }}
        >
          <div className="flex justify-between align-center" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '12px', flexWrap: 'wrap', gap: '10px' }}>
            <div className="flex align-center gap-sm">
              <Zap className="text-teal" size={22} style={{ color: apiSimStatus === 'waf_blocked' ? 'var(--color-rose)' : apiSimStatus === 'validation_error' ? 'var(--color-violet)' : 'var(--color-teal)' }} />
              <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#fff', letterSpacing: '0.03em' }}>
                ⚡ BỘ MÔ PHỎNG API THỜI GIAN THỰC (LIVE API VALIDATION SIMULATOR)
              </h2>
            </div>
            <div className="flex align-center gap-sm">
              {selectedRecord && (
                <span style={{ fontSize: '11px', background: 'rgba(255,255,255,0.05)', color: 'var(--text-secondary)', padding: '2px 8px', borderRadius: '12px', fontWeight: '500' }}>
                  Ca Test #{selectedRecordIdx !== null ? selectedRecordIdx + 1 : ''}
                </span>
              )}
              <button
                onClick={handleBatchRunAll}
                disabled={batchRunning}
                style={{
                  fontSize: '12px',
                  padding: '7px 14px',
                  background: batchRunning ? 'rgba(255,255,255,0.02)' : 'linear-gradient(135deg, rgba(45,212,191,0.15), rgba(45,212,191,0.05))',
                  border: '1px solid',
                  borderColor: batchRunning ? 'rgba(255,255,255,0.05)' : 'rgba(45,212,191,0.3)',
                  borderRadius: '8px',
                  color: batchRunning ? 'var(--text-muted)' : 'var(--color-teal)',
                  cursor: batchRunning ? 'not-allowed' : 'pointer',
                  fontWeight: 'bold',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  transition: 'all 0.2s',
                  whiteSpace: 'nowrap'
                }}
              >
                {batchRunning ? (
                  <>
                    <div style={{ width: '12px', height: '12px', border: '2px solid rgba(45,212,191,0.2)', borderTopColor: 'var(--color-teal)', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
                    Đang chạy {batchProgress}%...
                  </>
                ) : (
                  <>
                    <Zap size={13} />
                    ⚡ Chạy Tất Cả ({optimizedDataset.length} ca)
                  </>
                )}
              </button>
            </div>
          </div>

          {/* THANH TIẾN TRÌNH BATCH RUN */}
          {batchRunning && (
            <div style={{ marginBottom: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: 'var(--text-muted)', marginBottom: '4px' }}>
                <span>Đang kiểm duyệt toàn bộ dataset...</span>
                <span>{batchProgress}%</span>
              </div>
              <div style={{ height: '6px', background: 'rgba(255,255,255,0.04)', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${batchProgress}%`, background: 'linear-gradient(90deg, var(--color-teal), #0d9488)', borderRadius: '3px', transition: 'width 0.1s' }} />
              </div>
            </div>
          )}

          {/* KẾT QUẢ BATCH RUN SUMMARY */}
          {batchSummary && !batchRunning && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '10px', marginBottom: '8px' }}>
              <div style={{ background: 'rgba(45,212,191,0.06)', border: '1px solid rgba(45,212,191,0.2)', borderRadius: '8px', padding: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 'bold', color: 'var(--color-teal)', fontFamily: 'var(--font-mono)' }}>{batchSummary.total}</div>
                <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>TỔNG CA</div>
              </div>
              <div style={{ background: 'rgba(45,212,191,0.06)', border: '1px solid rgba(45,212,191,0.2)', borderRadius: '8px', padding: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 'bold', color: 'var(--color-teal)', fontFamily: 'var(--font-mono)' }}>{batchSummary.passed}</div>
                <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>HTTP 200 ✅</div>
              </div>
              <div style={{ background: 'rgba(167,139,250,0.06)', border: '1px solid rgba(167,139,250,0.2)', borderRadius: '8px', padding: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 'bold', color: 'var(--color-violet)', fontFamily: 'var(--font-mono)' }}>{batchSummary.validationErrors}</div>
                <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>HTTP 400 ⚠️</div>
              </div>
              <div style={{ background: 'rgba(244,63,94,0.06)', border: '1px solid rgba(244,63,94,0.2)', borderRadius: '8px', padding: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 'bold', color: 'var(--color-rose)', fontFamily: 'var(--font-mono)' }}>{batchSummary.wafBlocked}</div>
                <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>HTTP 403 🚫</div>
              </div>
            </div>
          )}

          {apiSimStatus === 'idle' ? (
            <div className="flex flex-col align-center justify-center gap-sm" style={{ padding: '40px 20px', color: 'var(--text-muted)', border: '1px dashed rgba(255,255,255,0.05)', borderRadius: '8px' }}>
              <Zap size={28} style={{ color: 'rgba(255,255,255,0.1)' }} />
              <p style={{ fontSize: '13px', textAlign: 'center' }}>
                Chọn một ca test bất kỳ trong bảng xem trước và bấm <b>"⚡ Test API"</b> để gửi payload giả lập kiểm thử.
              </p>
            </div>
          ) : (
            <div className="grid-2" style={{ gap: '20px' }}>
              {/* Cột trái: Payload được gửi lên */}
              <div className="flex flex-col gap-sm">
                <span style={{ fontSize: '12.5px', fontWeight: 'bold', color: 'var(--text-secondary)' }}>
                  📥 HTTP Request Payload (POST /api/v1/submit)
                </span>
                <pre 
                  style={{ 
                    background: 'rgba(15, 23, 42, 0.8)', 
                    border: '1px solid rgba(255,255,255,0.05)',
                    padding: '12px', 
                    borderRadius: '8px', 
                    fontSize: '11px', 
                    fontFamily: 'var(--font-mono)', 
                    color: '#a7f3d0', 
                    overflow: 'auto',
                    maxHeight: '180px',
                    margin: 0
                  }}
                >
                  {JSON.stringify(selectedRecord, null, 2)}
                </pre>
              </div>

              {/* Cột phải: Response trả về */}
              <div className="flex flex-col gap-sm">
                <div className="flex justify-between align-center">
                  <span style={{ fontSize: '12.5px', fontWeight: 'bold', color: 'var(--text-secondary)' }}>
                    📤 HTTP Response Status:
                  </span>
                  {apiSimStatus !== 'loading' && (
                    <span 
                      style={{ 
                        padding: '2px 8px', 
                        borderRadius: '4px', 
                        fontSize: '11px', 
                        fontWeight: 'bold',
                        background: 
                          apiSimStatus === 'success' ? 'rgba(45, 212, 191, 0.15)' : 
                          apiSimStatus === 'validation_error' ? 'rgba(167, 139, 250, 0.15)' : 
                          'rgba(244, 63, 94, 0.15)',
                        color: 
                          apiSimStatus === 'success' ? 'var(--color-teal)' : 
                          apiSimStatus === 'validation_error' ? 'var(--color-violet)' : 
                          'var(--color-rose)'
                      }}
                    >
                      HTTP {apiSimDetails?.status} {apiSimDetails?.statusText}
                    </span>
                  )}
                </div>

                {apiSimStatus === 'loading' ? (
                  <div className="flex align-center justify-center" style={{ flex: 1, minHeight: '120px', background: 'rgba(15, 23, 42, 0.4)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div className="flex flex-col align-center gap-sm">
                      <div style={{ width: '24px', height: '24px', border: '2px solid rgba(255,255,255,0.1)', borderTopColor: 'var(--color-teal)', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
                      <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Đang kiểm duyệt qua WAF & Sandbox API...</span>
                    </div>
                  </div>
                ) : (
                  <div style={{ position: 'relative' }}>
                    <pre 
                      style={{ 
                        background: 'rgba(15, 23, 42, 0.8)', 
                        border: '1px solid',
                        borderColor: 
                          apiSimStatus === 'success' ? 'rgba(45, 212, 191, 0.15)' : 
                          apiSimStatus === 'validation_error' ? 'rgba(167, 139, 250, 0.15)' : 
                          'rgba(244, 63, 94, 0.2)',
                        padding: '12px', 
                        borderRadius: '8px', 
                        fontSize: '11px', 
                        fontFamily: 'var(--font-mono)', 
                        color: 
                          apiSimStatus === 'success' ? '#2dd4bf' : 
                          apiSimStatus === 'validation_error' ? '#c084fc' : 
                          '#fda4af', 
                        overflow: 'auto',
                        maxHeight: '180px',
                        margin: 0
                      }}
                    >
                      {JSON.stringify(apiSimDetails, null, 2)}
                    </pre>
                    
                    {/* Cảnh báo WAF nhấp nháy đỏ cực ngầu */}
                    {apiSimStatus === 'waf_blocked' && (
                      <div 
                        style={{ 
                          marginTop: '8px',
                          padding: '8px 12px',
                          background: 'rgba(244, 63, 94, 0.1)',
                          border: '1px solid var(--color-rose)',
                          borderRadius: '6px',
                          fontSize: '11px',
                          color: 'var(--color-rose)',
                          animation: 'pulse 2s infinite',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '6px'
                        }}
                      >
                        <ShieldAlert size={14} />
                        <span><b>HỆ THỐNG AN NINH CHẶN GIAO DỊCH:</b> Tường lửa WAF đã khóa địa chỉ IP do hành vi injection.</span>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      )}
      
      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.7; }
        }
      `}</style>
    </div>
  );
};
